# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxOrder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxOrder
  pod 'RxSwift'
  pod 'RxCocoa'
  target 'RxOrderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxOrderUITests' do
    # Pods for testing
  end

end
